### ISSUE TITLE
ausführlicher und Beispiel des genauen Menüs also der genauen Ausgaben und Textführung

### ISSUE THREAD

**Issue by teach404W** [HEBK-BGM/Verwaltungssoftware_Team_4#20]
https://github.com/teach404W/Verwaltungssoftware_Team_4/blob/ca322280d8635d20a32863b4bb3720cb4dc65abd/Docs/Pflichtenheft/Pflichtenheft.md#L26

**Comment by Kevin-Kroeger** [comment]
Habe da schonmal eine Kleine Mindmap hinzugefügt, damit wir wissen wie das Aussehen könnte
