### ISSUE TITLE
Textuelle Beschreibung der Methoen fehlt

### ISSUE THREAD

**Issue by teach404W** [HEBK-BGM/Verwaltungssoftware_Team_4#21]
https://github.com/teach404W/Verwaltungssoftware_Team_4/blob/ca322280d8635d20a32863b4bb3720cb4dc65abd/Docs/Pflichtenheft/Pflichtenheft.md#L29

**Comment by Kevin-Kroeger** [comment]
guckt mal eben drüber ob das so passt.
